apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-mongo-deployment
  labels: 
    app: node-mongo-app
spec:
  selector:
    matchLabels:
      app: node-mongo-app
  replicas: 3
  template:
    metadata:
      labels:
        app: node-mongo-app
    spec:
      containers:
      - name: my-app
        image: gcr.io/skill-poc/nodejs-mongo-basic-image
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: node-mongo-service
  labels:
    app: node-mongo-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
  selector:
    app: node-mongo-app